//
// ApiextensionsV1ServiceReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ServiceReference holds a reference to Service.legacy.k8s.io */

public struct ApiextensionsV1ServiceReference: Codable {

    /** name is the name of the service. Required */
    public var name: String
    /** namespace is the namespace of the service. Required */
    public var namespace: String
    /** path is an optional URL path at which the webhook will be contacted. */
    public var path: String?
    /** port is an optional service port at which the webhook will be contacted. &#x60;port&#x60; should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility. */
    public var port: Int?

    public init(name: String, namespace: String, path: String?, port: Int?) {
        self.name = name
        self.namespace = namespace
        self.path = path
        self.port = port
    }


}

