//
// AppsV1beta1RollbackConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DEPRECATED. */

public struct AppsV1beta1RollbackConfig: Codable {

    /** The revision to rollback to. If set to 0, rollback to the last revision. */
    public var revision: Int64?

    public init(revision: Int64?) {
        self.revision = revision
    }


}

