//
// AppsV1beta1DeploymentRollback.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DEPRECATED. DeploymentRollback stores the information required to rollback a deployment. */

public struct AppsV1beta1DeploymentRollback: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    /** Required: This must match the Name of a deployment. */
    public var name: String
    public var rollbackTo: AppsV1beta1RollbackConfig
    /** The annotations to be updated to a deployment */
    public var updatedAnnotations: [String:String]?

    public init(apiVersion: String?, kind: String?, name: String, rollbackTo: AppsV1beta1RollbackConfig, updatedAnnotations: [String:String]?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.name = name
        self.rollbackTo = rollbackTo
        self.updatedAnnotations = updatedAnnotations
    }


}

