//
// ExtensionsV1beta1Scale.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** represents a scaling request for a resource. */

public struct ExtensionsV1beta1Scale: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var spec: ExtensionsV1beta1ScaleSpec?
    public var status: ExtensionsV1beta1ScaleStatus?

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, spec: ExtensionsV1beta1ScaleSpec?, status: ExtensionsV1beta1ScaleStatus?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.spec = spec
        self.status = status
    }


}

