//
// ExtensionsV1beta1SELinuxStrategyOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** SELinuxStrategyOptions defines the strategy type and any options used to create the strategy. Deprecated: use SELinuxStrategyOptions from policy API Group instead. */

public struct ExtensionsV1beta1SELinuxStrategyOptions: Codable {

    /** rule is the strategy that will dictate the allowable labels that may be set. */
    public var rule: String
    public var seLinuxOptions: V1SELinuxOptions?

    public init(rule: String, seLinuxOptions: V1SELinuxOptions?) {
        self.rule = rule
        self.seLinuxOptions = seLinuxOptions
    }


}

