//
// ExtensionsV1beta1IngressRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** IngressRule represents the rules mapping the paths under a specified host to the related backend services. Incoming requests are first evaluated for a host match, then routed to the backend associated with the matching IngressRuleValue. */

public struct ExtensionsV1beta1IngressRule: Codable {

    /** Host is the fully qualified domain name of a network host, as defined by RFC 3986. Note the following deviations from the \&quot;host\&quot; part of the URI as defined in the RFC: 1. IPs are not allowed. Currently an IngressRuleValue can only apply to the    IP in the Spec of the parent Ingress. 2. The &#x60;:&#x60; delimiter is not respected because ports are not allowed.    Currently the port of an Ingress is implicitly :80 for http and    :443 for https. Both these may change in the future. Incoming requests are matched against the host before the IngressRuleValue. If the host is unspecified, the Ingress routes all traffic based on the specified IngressRuleValue. */
    public var host: String?
    public var http: ExtensionsV1beta1HTTPIngressRuleValue?

    public init(host: String?, http: ExtensionsV1beta1HTTPIngressRuleValue?) {
        self.host = host
        self.http = http
    }


}

