//
// ExtensionsV1beta1ScaleSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** describes the attributes of a scale subresource */

public struct ExtensionsV1beta1ScaleSpec: Codable {

    /** desired number of instances for the scaled object. */
    public var replicas: Int?

    public init(replicas: Int?) {
        self.replicas = replicas
    }


}

