//
// ExtensionsV1beta1RunAsUserStrategyOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** RunAsUserStrategyOptions defines the strategy type and any options used to create the strategy. Deprecated: use RunAsUserStrategyOptions from policy API Group instead. */

public struct ExtensionsV1beta1RunAsUserStrategyOptions: Codable {

    /** ranges are the allowed ranges of uids that may be used. If you would like to force a single uid then supply a single range with the same start and end. Required for MustRunAs. */
    public var ranges: [ExtensionsV1beta1IDRange]?
    /** rule is the strategy that will dictate the allowable RunAsUser values that may be set. */
    public var rule: String

    public init(ranges: [ExtensionsV1beta1IDRange]?, rule: String) {
        self.ranges = ranges
        self.rule = rule
    }


}

