//
// ExtensionsV1beta1DeploymentStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DeploymentStrategy describes how to replace existing pods with new ones. */

public struct ExtensionsV1beta1DeploymentStrategy: Codable {

    public var rollingUpdate: ExtensionsV1beta1RollingUpdateDeployment?
    /** Type of deployment. Can be \&quot;Recreate\&quot; or \&quot;RollingUpdate\&quot;. Default is RollingUpdate. */
    public var type: String?

    public init(rollingUpdate: ExtensionsV1beta1RollingUpdateDeployment?, type: String?) {
        self.rollingUpdate = rollingUpdate
        self.type = type
    }


}

