//
// ExtensionsV1beta1IngressSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** IngressSpec describes the Ingress the user wishes to exist. */

public struct ExtensionsV1beta1IngressSpec: Codable {

    public var backend: ExtensionsV1beta1IngressBackend?
    /** A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend. */
    public var rules: [ExtensionsV1beta1IngressRule]?
    /** TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI. */
    public var tls: [ExtensionsV1beta1IngressTLS]?

    public init(backend: ExtensionsV1beta1IngressBackend?, rules: [ExtensionsV1beta1IngressRule]?, tls: [ExtensionsV1beta1IngressTLS]?) {
        self.backend = backend
        self.rules = rules
        self.tls = tls
    }


}

