//
// FlowcontrolV1alpha1Subject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account. */

public struct FlowcontrolV1alpha1Subject: Codable {

    public var group: V1alpha1GroupSubject?
    /** Required */
    public var kind: String
    public var serviceAccount: V1alpha1ServiceAccountSubject?
    public var user: V1alpha1UserSubject?

    public init(group: V1alpha1GroupSubject?, kind: String, serviceAccount: V1alpha1ServiceAccountSubject?, user: V1alpha1UserSubject?) {
        self.group = group
        self.kind = kind
        self.serviceAccount = serviceAccount
        self.user = user
    }


}

