//
// NetworkingV1beta1Ingress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Ingress is a collection of rules that allow inbound connections to reach the endpoints defined by a backend. An Ingress can be configured to give services externally-reachable urls, load balance traffic, terminate SSL, offer name based virtual hosting etc. */

public struct NetworkingV1beta1Ingress: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var spec: NetworkingV1beta1IngressSpec?
    public var status: NetworkingV1beta1IngressStatus?

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, spec: NetworkingV1beta1IngressSpec?, status: NetworkingV1beta1IngressStatus?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.spec = spec
        self.status = status
    }


}

