//
// NetworkingV1beta1HTTPIngressRuleValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://&lt;host&gt;/&lt;path&gt;?&lt;searchpart&gt; -&gt; backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last &#39;/&#39; and before the first &#39;?&#39; or &#39;#&#39;. */

public struct NetworkingV1beta1HTTPIngressRuleValue: Codable {

    /** A collection of paths that map requests to backends. */
    public var paths: [NetworkingV1beta1HTTPIngressPath]

    public init(paths: [NetworkingV1beta1HTTPIngressPath]) {
        self.paths = paths
    }


}

