//
// NetworkingV1beta1HTTPIngressPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** HTTPIngressPath associates a path regex with a backend. Incoming urls matching the path are forwarded to the backend. */

public struct NetworkingV1beta1HTTPIngressPath: Codable {

    public var backend: NetworkingV1beta1IngressBackend
    /** Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional \&quot;path\&quot; part of a URL as defined by RFC 3986. Paths must begin with a &#39;/&#39;. If unspecified, the path defaults to a catch all sending traffic to the backend. */
    public var path: String?

    public init(backend: NetworkingV1beta1IngressBackend, path: String?) {
        self.backend = backend
        self.path = path
    }


}

