//
// NetworkingV1beta1IngressBackend.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** IngressBackend describes all endpoints for a given service and port. */

public struct NetworkingV1beta1IngressBackend: Codable {

    /** Specifies the name of the referenced service. */
    public var serviceName: String
    /** Specifies the port of the referenced service. */
//    public var servicePort: Any

//    public init(serviceName: String, servicePort: Any) {
//        self.serviceName = serviceName
//        self.servicePort = servicePort
//    }


}

