//
// PolicyV1beta1AllowedFlexVolume.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** AllowedFlexVolume represents a single Flexvolume that is allowed to be used. */

public struct PolicyV1beta1AllowedFlexVolume: Codable {

    /** driver is the name of the Flexvolume driver. */
    public var driver: String

    public init(driver: String) {
        self.driver = driver
    }


}

