//
// PolicyV1beta1PodSecurityPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodSecurityPolicy governs the ability to make requests that affect the Security Context that will be applied to a pod and container. */

public struct PolicyV1beta1PodSecurityPolicy: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var spec: PolicyV1beta1PodSecurityPolicySpec?

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, spec: PolicyV1beta1PodSecurityPolicySpec?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.spec = spec
    }


}

