//
// PolicyV1beta1AllowedCSIDriver.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** AllowedCSIDriver represents a single inline CSI Driver that is allowed to be used. */

public struct PolicyV1beta1AllowedCSIDriver: Codable {

    /** Name is the registered name of the CSI driver */
    public var name: String

    public init(name: String) {
        self.name = name
    }


}

