//
// V1Affinity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Affinity is a group of affinity scheduling rules. */

public struct V1Affinity: Codable {

    public var nodeAffinity: V1NodeAffinity?
    public var podAffinity: V1PodAffinity?
    public var podAntiAffinity: V1PodAntiAffinity?

    public init(nodeAffinity: V1NodeAffinity?, podAffinity: V1PodAffinity?, podAntiAffinity: V1PodAntiAffinity?) {
        self.nodeAffinity = nodeAffinity
        self.podAffinity = podAffinity
        self.podAntiAffinity = podAntiAffinity
    }


}

