//
// V1AggregationRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** AggregationRule describes how to locate ClusterRoles to aggregate into the ClusterRole */

public struct V1AggregationRule: Codable {

    /** ClusterRoleSelectors holds a list of selectors which will be used to find ClusterRoles and create the rules. If any of the selectors match, then the ClusterRole&#39;s permissions will be added */
    public var clusterRoleSelectors: [V1LabelSelector]?

    public init(clusterRoleSelectors: [V1LabelSelector]?) {
        self.clusterRoleSelectors = clusterRoleSelectors
    }


}

