//
// V1alpha1Overhead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Overhead structure represents the resource overhead associated with running a pod. */

public struct V1alpha1Overhead: Codable {

    /** PodFixed represents the fixed resource overhead associated with running a pod. */
    public var podFixed: [String:String]?

    public init(podFixed: [String:String]?) {
        self.podFixed = podFixed
    }


}

