//
// V1alpha1GroupSubject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** GroupSubject holds detailed information for group-kind subject. */

public struct V1alpha1GroupSubject: Codable {

    /** name is the user group that matches, or \&quot;*\&quot; to match all user groups. See https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/user/user.go for some well-known group names. Required. */
    public var name: String

    public init(name: String) {
        self.name = name
    }


}

