//
// V1alpha1ResourcePolicyRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ResourcePolicyRule is a predicate that matches some resource requests, testing the request&#39;s verb and the target resource. A ResourcePolicyRule matches a resource request if and only if: (a) at least one member of verbs matches the request, (b) at least one member of apiGroups matches the request, (c) at least one member of resources matches the request, and (d) least one member of namespaces matches the request. */

public struct V1alpha1ResourcePolicyRule: Codable {

    /** &#x60;apiGroups&#x60; is a list of matching API groups and may not be empty. \&quot;*\&quot; matches all API groups and, if present, must be the only entry. Required. */
    public var apiGroups: [String]
    /** &#x60;clusterScope&#x60; indicates whether to match requests that do not specify a namespace (which happens either because the resource is not namespaced or the request targets all namespaces). If this field is omitted or false then the &#x60;namespaces&#x60; field must contain a non-empty list. */
    public var clusterScope: Bool?
    /** &#x60;namespaces&#x60; is a list of target namespaces that restricts matches.  A request that specifies a target namespace matches only if either (a) this list contains that target namespace or (b) this list contains \&quot;*\&quot;.  Note that \&quot;*\&quot; matches any specified namespace but does not match a request that _does not specify_ a namespace (see the &#x60;clusterScope&#x60; field for that). This list may be empty, but only if &#x60;clusterScope&#x60; is true. */
    public var namespaces: [String]?
    /** &#x60;resources&#x60; is a list of matching resources (i.e., lowercase and plural) with, if desired, subresource.  For example, [ \&quot;services\&quot;, \&quot;nodes/status\&quot; ].  This list may not be empty. \&quot;*\&quot; matches all resources and, if present, must be the only entry. Required. */
    public var resources: [String]
    /** &#x60;verbs&#x60; is a list of matching verbs and may not be empty. \&quot;*\&quot; matches all verbs and, if present, must be the only entry. Required. */
    public var verbs: [String]

    public init(apiGroups: [String], clusterScope: Bool?, namespaces: [String]?, resources: [String], verbs: [String]) {
        self.apiGroups = apiGroups
        self.clusterScope = clusterScope
        self.namespaces = namespaces
        self.resources = resources
        self.verbs = verbs
    }


}

