//
// V1alpha1UserSubject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** UserSubject holds detailed information for user-kind subject. */

public struct V1alpha1UserSubject: Codable {

    /** &#x60;name&#x60; is the username that matches, or \&quot;*\&quot; to match all usernames. Required. */
    public var name: String

    public init(name: String) {
        self.name = name
    }


}

