//
// V1alpha1PriorityLevelConfigurationReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PriorityLevelConfigurationReference contains information that points to the \&quot;request-priority\&quot; being used. */

public struct V1alpha1PriorityLevelConfigurationReference: Codable {

    /** &#x60;name&#x60; is the name of the priority level configuration being referenced Required. */
    public var name: String

    public init(name: String) {
        self.name = name
    }


}

