//
// V1alpha1PriorityLevelConfigurationList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PriorityLevelConfigurationList is a list of PriorityLevelConfiguration objects. */

public struct V1alpha1PriorityLevelConfigurationList: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** &#x60;items&#x60; is a list of request-priorities. */
    public var items: [V1alpha1PriorityLevelConfiguration]
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ListMeta?

    public init(apiVersion: String?, items: [V1alpha1PriorityLevelConfiguration], kind: String?, metadata: V1ListMeta?) {
        self.apiVersion = apiVersion
        self.items = items
        self.kind = kind
        self.metadata = metadata
    }


}

