//
// V1alpha1WebhookThrottleConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** WebhookThrottleConfig holds the configuration for throttling events */

public struct V1alpha1WebhookThrottleConfig: Codable {

    /** ThrottleBurst is the maximum number of events sent at the same moment default 15 QPS */
    public var burst: Int64?
    /** ThrottleQPS maximum number of batches per second default 10 QPS */
    public var qps: Int64?

    public init(burst: Int64?, qps: Int64?) {
        self.burst = burst
        self.qps = qps
    }


}

