//
// V1alpha1ServiceAccountSubject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ServiceAccountSubject holds detailed information for service-account-kind subject. */

public struct V1alpha1ServiceAccountSubject: Codable {

    /** &#x60;name&#x60; is the name of matching ServiceAccount objects, or \&quot;*\&quot; to match regardless of name. Required. */
    public var name: String
    /** &#x60;namespace&#x60; is the namespace of matching ServiceAccount objects. Required. */
    public var namespace: String

    public init(name: String, namespace: String) {
        self.name = name
        self.namespace = namespace
    }


}

