//
// V1alpha1FlowSchemaStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** FlowSchemaStatus represents the current state of a FlowSchema. */

public struct V1alpha1FlowSchemaStatus: Codable {

    /** &#x60;conditions&#x60; is a list of the current states of FlowSchema. */
    public var conditions: [V1alpha1FlowSchemaCondition]?

    public init(conditions: [V1alpha1FlowSchemaCondition]?) {
        self.conditions = conditions
    }


}

