//
// V1alpha1PodPresetSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodPresetSpec is a description of a pod preset. */

public struct V1alpha1PodPresetSpec: Codable {

    /** Env defines the collection of EnvVar to inject into containers. */
    public var env: [V1EnvVar]?
    /** EnvFrom defines the collection of EnvFromSource to inject into containers. */
    public var envFrom: [V1EnvFromSource]?
    public var selector: V1LabelSelector?
    /** VolumeMounts defines the collection of VolumeMount to inject into containers. */
    public var volumeMounts: [V1VolumeMount]?
    /** Volumes defines the collection of Volume to inject into the pod. */
    public var volumes: [V1Volume]?

    public init(env: [V1EnvVar]?, envFrom: [V1EnvFromSource]?, selector: V1LabelSelector?, volumeMounts: [V1VolumeMount]?, volumes: [V1Volume]?) {
        self.env = env
        self.envFrom = envFrom
        self.selector = selector
        self.volumeMounts = volumeMounts
        self.volumes = volumes
    }


}

