//
// V1alpha1Policy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Policy defines the configuration of how audit events are logged */

public struct V1alpha1Policy: Codable {

    /** The Level that all requests are recorded at. available options: None, Metadata, Request, RequestResponse required */
    public var level: String
    /** Stages is a list of stages for which events are created. */
    public var stages: [String]?

    public init(level: String, stages: [String]?) {
        self.level = level
        self.stages = stages
    }


}

