//
// V1alpha1FlowSchemaSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** FlowSchemaSpec describes how the FlowSchema&#39;s specification looks like. */

public struct V1alpha1FlowSchemaSpec: Codable {

    public var distinguisherMethod: V1alpha1FlowDistinguisherMethod?
    /** &#x60;matchingPrecedence&#x60; is used to choose among the FlowSchemas that match a given request. The chosen FlowSchema is among those with the numerically lowest (which we take to be logically highest) MatchingPrecedence.  Each MatchingPrecedence value must be non-negative. Note that if the precedence is not specified or zero, it will be set to 1000 as default. */
    public var matchingPrecedence: Int?
    public var priorityLevelConfiguration: V1alpha1PriorityLevelConfigurationReference
    /** &#x60;rules&#x60; describes which requests will match this flow schema. This FlowSchema matches a request if and only if at least one member of rules matches the request. if it is an empty slice, there will be no requests matching the FlowSchema. */
    public var rules: [V1alpha1PolicyRulesWithSubjects]?

    public init(distinguisherMethod: V1alpha1FlowDistinguisherMethod?, matchingPrecedence: Int?, priorityLevelConfiguration: V1alpha1PriorityLevelConfigurationReference, rules: [V1alpha1PolicyRulesWithSubjects]?) {
        self.distinguisherMethod = distinguisherMethod
        self.matchingPrecedence = matchingPrecedence
        self.priorityLevelConfiguration = priorityLevelConfiguration
        self.rules = rules
    }


}

