//
// V1alpha1VolumeError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** VolumeError captures an error encountered during a volume operation. */

public struct V1alpha1VolumeError: Codable {

    /** String detailing the error encountered during Attach or Detach operation. This string maybe logged, so it should not contain sensitive information. */
    public var message: String?
    /** Time the error was encountered. */
    public var time: Date?

    public init(message: String?, time: Date?) {
        self.message = message
        self.time = time
    }


}

