//
// V1alpha1VolumeAttachmentSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** VolumeAttachmentSpec is the specification of a VolumeAttachment request. */

public struct V1alpha1VolumeAttachmentSpec: Codable {

    /** Attacher indicates the name of the volume driver that MUST handle this request. This is the name returned by GetPluginName(). */
    public var attacher: String
    /** The node that the volume should be attached to. */
    public var nodeName: String
    public var source: V1alpha1VolumeAttachmentSource

    public init(attacher: String, nodeName: String, source: V1alpha1VolumeAttachmentSource) {
        self.attacher = attacher
        self.nodeName = nodeName
        self.source = source
    }


}

