//
// V1APIGroupList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** APIGroupList is a list of APIGroup, to allow clients to discover the API at /apis. */

public struct V1APIGroupList: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** groups is a list of APIGroup. */
    public var groups: [V1APIGroup]
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?

    public init(apiVersion: String?, groups: [V1APIGroup], kind: String?) {
        self.apiVersion = apiVersion
        self.groups = groups
        self.kind = kind
    }


}

