//
// V1AttachedVolume.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** AttachedVolume describes a volume attached to a node */

public struct V1AttachedVolume: Codable {

    /** DevicePath represents the device path where the volume should be available */
    public var devicePath: String
    /** Name of the attached volume */
    public var name: String

    public init(devicePath: String, name: String) {
        self.devicePath = devicePath
        self.name = name
    }


}

