//
// V1AzureFileVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** AzureFile represents an Azure File Service mount on the host and bind mount to the pod. */

public struct V1AzureFileVolumeSource: Codable {

    /** Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    public var readOnly: Bool?
    /** the name of secret that contains Azure Storage Account Name and Key */
    public var secretName: String
    /** Share Name */
    public var shareName: String

    public init(readOnly: Bool?, secretName: String, shareName: String) {
        self.readOnly = readOnly
        self.secretName = secretName
        self.shareName = shareName
    }


}

