//
// V1beta1Endpoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Endpoint represents a single logical \&quot;backend\&quot; implementing a service. */

public struct V1beta1Endpoint: Codable {

    /** addresses of this endpoint. The contents of this field are interpreted according to the corresponding EndpointSlice addressType field. Consumers must handle different types of addresses in the context of their own capabilities. This must contain at least one address but no more than 100. */
    public var addresses: [String]
    public var conditions: V1beta1EndpointConditions?
    /** hostname of this endpoint. This field may be used by consumers of endpoints to distinguish endpoints from each other (e.g. in DNS names). Multiple endpoints which use the same hostname should be considered fungible (e.g. multiple A values in DNS). Must pass DNS Label (RFC 1123) validation. */
    public var hostname: String?
    public var targetRef: V1ObjectReference?
    /** topology contains arbitrary topology information associated with the endpoint. These key/value pairs must conform with the label format. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels Topology may include a maximum of 16 key/value pairs. This includes, but is not limited to the following well known keys: * kubernetes.io/hostname: the value indicates the hostname of the node   where the endpoint is located. This should match the corresponding   node label. * topology.kubernetes.io/zone: the value indicates the zone where the   endpoint is located. This should match the corresponding node label. * topology.kubernetes.io/region: the value indicates the region where the   endpoint is located. This should match the corresponding node label. */
    public var topology: [String:String]?

    public init(addresses: [String], conditions: V1beta1EndpointConditions?, hostname: String?, targetRef: V1ObjectReference?, topology: [String:String]?) {
        self.addresses = addresses
        self.conditions = conditions
        self.hostname = hostname
        self.targetRef = targetRef
        self.topology = topology
    }


}

