//
// V1beta1CronJobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CronJobStatus represents the current state of a cron job. */

public struct V1beta1CronJobStatus: Codable {

    /** A list of pointers to currently running jobs. */
    public var active: [V1ObjectReference]?
    /** Information when was the last time the job was successfully scheduled. */
    public var lastScheduleTime: Date?

    public init(active: [V1ObjectReference]?, lastScheduleTime: Date?) {
        self.active = active
        self.lastScheduleTime = lastScheduleTime
    }


}

