//
// V1beta1Subject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Subject contains a reference to the object or user identities a role binding applies to.  This can either hold a direct API object reference, or a value for non-objects such as user and group names. */

public struct V1beta1Subject: Codable {

    /** APIGroup holds the API group of the referenced subject. Defaults to \&quot;\&quot; for ServiceAccount subjects. Defaults to \&quot;rbac.authorization.k8s.io\&quot; for User and Group subjects. */
    public var apiGroup: String?
    /** Kind of object being referenced. Values defined by this API group are \&quot;User\&quot;, \&quot;Group\&quot;, and \&quot;ServiceAccount\&quot;. If the Authorizer does not recognized the kind value, the Authorizer should report an error. */
    public var kind: String
    /** Name of the object being referenced. */
    public var name: String
    /** Namespace of the referenced object.  If the object kind is non-namespace, such as \&quot;User\&quot; or \&quot;Group\&quot;, and this value is not empty the Authorizer should report an error. */
    public var namespace: String?

    public init(apiGroup: String?, kind: String, name: String, namespace: String?) {
        self.apiGroup = apiGroup
        self.kind = kind
        self.name = name
        self.namespace = namespace
    }


}

