//
// V1beta1CustomResourceValidation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CustomResourceValidation is a list of validation methods for CustomResources. */

public struct V1beta1CustomResourceValidation: Codable {

    public var openAPIV3Schema: V1beta1JSONSchemaProps?


}

