//
// V1beta1EndpointSlice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** EndpointSlice represents a subset of the endpoints that implement a service. For a given service there may be multiple EndpointSlice objects, selected by labels, which must be joined to produce the full set of endpoints. */

public struct V1beta1EndpointSlice: Codable {

    /** addressType specifies the type of address carried by this EndpointSlice. All addresses in this slice must be the same type. This field is immutable after creation. The following address types are currently supported: * IPv4: Represents an IPv4 Address. * IPv6: Represents an IPv6 Address. * FQDN: Represents a Fully Qualified Domain Name. */
    public var addressType: String
    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** endpoints is a list of unique endpoints in this slice. Each slice may include a maximum of 1000 endpoints. */
    public var endpoints: [V1beta1Endpoint]
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    /** ports specifies the list of network ports exposed by each endpoint in this slice. Each port must have a unique name. When ports is empty, it indicates that there are no defined ports. When a port is defined with a nil port value, it indicates \&quot;all ports\&quot;. Each slice may include a maximum of 100 ports. */
    public var ports: [V1beta1EndpointPort]?

    public init(addressType: String, apiVersion: String?, endpoints: [V1beta1Endpoint], kind: String?, metadata: V1ObjectMeta?, ports: [V1beta1EndpointPort]?) {
        self.addressType = addressType
        self.apiVersion = apiVersion
        self.endpoints = endpoints
        self.kind = kind
        self.metadata = metadata
        self.ports = ports
    }


}

