//
// V1beta1CertificateSigningRequestSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** This information is immutable after the request is created. Only the Request and Usages fields can be set on creation, other fields are derived by Kubernetes and cannot be modified by users. */

public struct V1beta1CertificateSigningRequestSpec: Codable {

    /** Extra information about the requesting user. See user.Info interface for details. */
    public var extra: [String:[String]]?
    /** Group information about the requesting user. See user.Info interface for details. */
    public var groups: [String]?
    /** Base64-encoded PKCS#10 CSR data */
    public var request: Data
    /** UID information about the requesting user. See user.Info interface for details. */
    public var uid: String?
    /** allowedUsages specifies a set of usage contexts the key will be valid for. See: https://tools.ietf.org/html/rfc5280#section-4.2.1.3      https://tools.ietf.org/html/rfc5280#section-4.2.1.12 */
    public var usages: [String]?
    /** Information about the requesting user. See user.Info interface for details. */
    public var username: String?

    public init(extra: [String:[String]]?, groups: [String]?, request: Data, uid: String?, usages: [String]?, username: String?) {
        self.extra = extra
        self.groups = groups
        self.request = request
        self.uid = uid
        self.usages = usages
        self.username = username
    }


}

