//
// V1beta1CertificateSigningRequestStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V1beta1CertificateSigningRequestStatus: Codable {

    /** If request was approved, the controller will place the issued certificate here. */
    public var certificate: Data?
    /** Conditions applied to the request, such as approval or denial. */
    public var conditions: [V1beta1CertificateSigningRequestCondition]?

    public init(certificate: Data?, conditions: [V1beta1CertificateSigningRequestCondition]?) {
        self.certificate = certificate
        self.conditions = conditions
    }


}

