//
// V1beta1Eviction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Eviction evicts a pod from its node subject to certain policies and safety constraints. This is a subresource of Pod.  A request to cause such an eviction is created by POSTing to .../pods/&lt;pod name&gt;/evictions. */

public struct V1beta1Eviction: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    public var deleteOptions: V1DeleteOptions?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?

    public init(apiVersion: String?, deleteOptions: V1DeleteOptions?, kind: String?, metadata: V1ObjectMeta?) {
        self.apiVersion = apiVersion
        self.deleteOptions = deleteOptions
        self.kind = kind
        self.metadata = metadata
    }


}

