//
// V1beta1SubjectAccessReviewStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** SubjectAccessReviewStatus */

public struct V1beta1SubjectAccessReviewStatus: Codable {

    /** Allowed is required. True if the action would be allowed, false otherwise. */
    public var allowed: Bool
    /** Denied is optional. True if the action would be denied, otherwise false. If both allowed is false and denied is false, then the authorizer has no opinion on whether to authorize the action. Denied may not be true if Allowed is true. */
    public var denied: Bool?
    /** EvaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request. */
    public var evaluationError: String?
    /** Reason is optional.  It indicates why a request was allowed or denied. */
    public var reason: String?

    public init(allowed: Bool, denied: Bool?, evaluationError: String?, reason: String?) {
        self.allowed = allowed
        self.denied = denied
        self.evaluationError = evaluationError
        self.reason = reason
    }


}

