//
// V1beta1PodDisruptionBudgetStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system. */

public struct V1beta1PodDisruptionBudgetStatus: Codable {

    /** current number of healthy pods */
    public var currentHealthy: Int
    /** minimum desired number of healthy pods */
    public var desiredHealthy: Int
    /** DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn&#39;t occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions. */
    public var disruptedPods: [String:Date]?
    /** Number of pod disruptions that are currently allowed. */
    public var disruptionsAllowed: Int
    /** total number of pods counted by this disruption budget */
    public var expectedPods: Int
    /** Most recent generation observed when updating this PDB status. PodDisruptionsAllowed and other status information is valid only if observedGeneration equals to PDB&#39;s object generation. */
    public var observedGeneration: Int64?

    public init(currentHealthy: Int, desiredHealthy: Int, disruptedPods: [String:Date]?, disruptionsAllowed: Int, expectedPods: Int, observedGeneration: Int64?) {
        self.currentHealthy = currentHealthy
        self.desiredHealthy = desiredHealthy
        self.disruptedPods = disruptedPods
        self.disruptionsAllowed = disruptionsAllowed
        self.expectedPods = expectedPods
        self.observedGeneration = observedGeneration
    }


}

