//
// V1beta1EventSeries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time. */

public struct V1beta1EventSeries: Codable {

    /** Number of occurrences in this series up to the last heartbeat time */
    public var count: Int
    /** Time when last Event from the series was seen before last heartbeat. */
    public var lastObservedTime: Date
    /** Information whether this series is ongoing or finished. Deprecated. Planned removal for 1.18 */
    public var state: String

    public init(count: Int, lastObservedTime: Date, state: String) {
        self.count = count
        self.lastObservedTime = lastObservedTime
        self.state = state
    }


}

