//
// V1beta1RoleBinding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** RoleBinding references a role, but does not contain it.  It can reference a Role in the same namespace or a ClusterRole in the global namespace. It adds who information via Subjects and namespace information by which namespace it exists in.  RoleBindings in a given namespace only have effect in that namespace. Deprecated in v1.17 in favor of rbac.authorization.k8s.io/v1 RoleBinding, and will no longer be served in v1.20. */

public struct V1beta1RoleBinding: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var roleRef: V1beta1RoleRef
    /** Subjects holds references to the objects the role applies to. */
    public var subjects: [V1beta1Subject]?

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, roleRef: V1beta1RoleRef, subjects: [V1beta1Subject]?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.roleRef = roleRef
        self.subjects = subjects
    }


}

