//
// V1beta1EndpointConditions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** EndpointConditions represents the current condition of an endpoint. */

public struct V1beta1EndpointConditions: Codable {

    /** ready indicates that this endpoint is prepared to receive traffic, according to whatever system is managing the endpoint. A nil value indicates an unknown state. In most cases consumers should interpret this unknown state as ready. */
    public var ready: Bool?

    public init(ready: Bool?) {
        self.ready = ready
    }


}

