//
// V1beta1DaemonSetUpdateStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V1beta1DaemonSetUpdateStrategy: Codable {

    public var rollingUpdate: V1beta1RollingUpdateDaemonSet?
    /** Type of daemon set update. Can be \&quot;RollingUpdate\&quot; or \&quot;OnDelete\&quot;. Default is OnDelete. */
    public var type: String?

    public init(rollingUpdate: V1beta1RollingUpdateDaemonSet?, type: String?) {
        self.rollingUpdate = rollingUpdate
        self.type = type
    }


}

