//
// V1beta1TokenReviewStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** TokenReviewStatus is the result of the token authentication request. */

public struct V1beta1TokenReviewStatus: Codable {

    /** Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token&#39;s audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is \&quot;true\&quot;, the token is valid against the audience of the Kubernetes API server. */
    public var audiences: [String]?
    /** Authenticated indicates that the token was associated with a known user. */
    public var authenticated: Bool?
    /** Error indicates that the token couldn&#39;t be checked */
    public var error: String?
    public var user: V1beta1UserInfo?

    public init(audiences: [String]?, authenticated: Bool?, error: String?, user: V1beta1UserInfo?) {
        self.audiences = audiences
        self.authenticated = authenticated
        self.error = error
        self.user = user
    }


}

