//
// V1beta1LeaseSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** LeaseSpec is a specification of a Lease. */

public struct V1beta1LeaseSpec: Codable {

    /** acquireTime is a time when the current lease was acquired. */
    public var acquireTime: Date?
    /** holderIdentity contains the identity of the holder of a current lease. */
    public var holderIdentity: String?
    /** leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measure against time of last observed RenewTime. */
    public var leaseDurationSeconds: Int?
    /** leaseTransitions is the number of transitions of a lease between holders. */
    public var leaseTransitions: Int?
    /** renewTime is a time when the current holder of a lease has last updated the lease. */
    public var renewTime: Date?

    public init(acquireTime: Date?, holderIdentity: String?, leaseDurationSeconds: Int?, leaseTransitions: Int?, renewTime: Date?) {
        self.acquireTime = acquireTime
        self.holderIdentity = holderIdentity
        self.leaseDurationSeconds = leaseDurationSeconds
        self.leaseTransitions = leaseTransitions
        self.renewTime = renewTime
    }


}

