//
// V1beta1StatefulSetStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** StatefulSetStatus represents the current state of a StatefulSet. */

public struct V1beta1StatefulSetStatus: Codable {

    /** collisionCount is the count of hash collisions for the StatefulSet. The StatefulSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision. */
    public var collisionCount: Int?
    /** Represents the latest available observations of a statefulset&#39;s current state. */
    public var conditions: [V1beta1StatefulSetCondition]?
    /** currentReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version indicated by currentRevision. */
    public var currentReplicas: Int?
    /** currentRevision, if not empty, indicates the version of the StatefulSet used to generate Pods in the sequence [0,currentReplicas). */
    public var currentRevision: String?
    /** observedGeneration is the most recent generation observed for this StatefulSet. It corresponds to the StatefulSet&#39;s generation, which is updated on mutation by the API Server. */
    public var observedGeneration: Int64?
    /** readyReplicas is the number of Pods created by the StatefulSet controller that have a Ready Condition. */
    public var readyReplicas: Int?
    /** replicas is the number of Pods created by the StatefulSet controller. */
    public var replicas: Int
    /** updateRevision, if not empty, indicates the version of the StatefulSet used to generate Pods in the sequence [replicas-updatedReplicas,replicas) */
    public var updateRevision: String?
    /** updatedReplicas is the number of Pods created by the StatefulSet controller from the StatefulSet version indicated by updateRevision. */
    public var updatedReplicas: Int?

    public init(collisionCount: Int?, conditions: [V1beta1StatefulSetCondition]?, currentReplicas: Int?, currentRevision: String?, observedGeneration: Int64?, readyReplicas: Int?, replicas: Int, updateRevision: String?, updatedReplicas: Int?) {
        self.collisionCount = collisionCount
        self.conditions = conditions
        self.currentReplicas = currentReplicas
        self.currentRevision = currentRevision
        self.observedGeneration = observedGeneration
        self.readyReplicas = readyReplicas
        self.replicas = replicas
        self.updateRevision = updateRevision
        self.updatedReplicas = updatedReplicas
    }


}

