//
// V1beta1ExternalDocumentation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ExternalDocumentation allows referencing an external resource for extended documentation. */

public struct V1beta1ExternalDocumentation: Codable {

    public var _description: String?
    public var url: String?

    public init(_description: String?, url: String?) {
        self._description = _description
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case url
    }


}

