//
// V1beta1PodDisruptionBudgetSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodDisruptionBudgetSpec is a description of a PodDisruptionBudget. */

public struct V1beta1PodDisruptionBudgetSpec: Codable {

    /** An eviction is allowed if at most \&quot;maxUnavailable\&quot; pods selected by \&quot;selector\&quot; are unavailable after the eviction, i.e. even in absence of the evicted pod. For example, one can prevent all voluntary evictions by specifying 0. This is a mutually exclusive setting with \&quot;minAvailable\&quot;. */
    public var maxUnavailable: Int?
    /** An eviction is allowed if at least \&quot;minAvailable\&quot; pods selected by \&quot;selector\&quot; will still be available after the eviction, i.e. even in the absence of the evicted pod.  So for example you can prevent all voluntary evictions by specifying \&quot;100%\&quot;. */
    public var minAvailable: Int?
    public var selector: V1LabelSelector?

}

