//
// V1beta1CustomResourceDefinitionVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CustomResourceDefinitionVersion describes a version for CRD. */

public struct V1beta1CustomResourceDefinitionVersion: Codable {

    /** additionalPrinterColumns specifies additional columns returned in Table output. See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables for details. Top-level and per-version columns are mutually exclusive. Per-version columns must not all be set to identical values (top-level columns should be used instead). If no top-level or per-version columns are specified, a single column displaying the age of the custom resource is used. */
    public var additionalPrinterColumns: [V1beta1CustomResourceColumnDefinition]?
    /** name is the version name, e.g. “v1”, “v2beta1”, etc. The custom resources are served under this version at &#x60;/apis/&lt;group&gt;/&lt;version&gt;/...&#x60; if &#x60;served&#x60; is true. */
    public var name: String
    public var schema: V1beta1CustomResourceValidation?
    /** served is a flag enabling/disabling this version from being served via REST APIs */
    public var served: Bool
    /** storage indicates this version should be used when persisting custom resources to storage. There must be exactly one version with storage&#x3D;true. */
    public var storage: Bool
    public var subresources: V1beta1CustomResourceSubresources?

    public init(additionalPrinterColumns: [V1beta1CustomResourceColumnDefinition]?, name: String, schema: V1beta1CustomResourceValidation?, served: Bool, storage: Bool, subresources: V1beta1CustomResourceSubresources?) {
        self.additionalPrinterColumns = additionalPrinterColumns
        self.name = name
        self.schema = schema
        self.served = served
        self.storage = storage
        self.subresources = subresources
    }


}

