//
// V1beta1CustomResourceSubresources.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CustomResourceSubresources defines the status and scale subresources for CustomResources. */

public struct V1beta1CustomResourceSubresources: Codable {

    public var scale: V1beta1CustomResourceSubresourceScale?
    /** status indicates the custom resource should serve a &#x60;/status&#x60; subresource. When enabled: 1. requests to the custom resource primary endpoint ignore changes to the &#x60;status&#x60; stanza of the object. 2. requests to the custom resource &#x60;/status&#x60; subresource ignore changes to anything other than the &#x60;status&#x60; stanza of the object. */
    public var status: String?

}

