//
// V1beta2DaemonSetUpdateStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet. */

public struct V1beta2DaemonSetUpdateStrategy: Codable {

    public var rollingUpdate: V1beta2RollingUpdateDaemonSet?
    /** Type of daemon set update. Can be \&quot;RollingUpdate\&quot; or \&quot;OnDelete\&quot;. Default is RollingUpdate. */
    public var type: String?

    public init(rollingUpdate: V1beta2RollingUpdateDaemonSet?, type: String?) {
        self.rollingUpdate = rollingUpdate
        self.type = type
    }


}

