//
// V1beta1NetworkPolicyPeer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DEPRECATED 1.9 - This group version of NetworkPolicyPeer is deprecated by networking/v1/NetworkPolicyPeer. */

public struct V1beta1NetworkPolicyPeer: Codable {

    public var ipBlock: V1beta1IPBlock?
    public var namespaceSelector: V1LabelSelector?
    public var podSelector: V1LabelSelector?

    public init(ipBlock: V1beta1IPBlock?, namespaceSelector: V1LabelSelector?, podSelector: V1LabelSelector?) {
        self.ipBlock = ipBlock
        self.namespaceSelector = namespaceSelector
        self.podSelector = podSelector
    }


}

