//
// V1Binding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Binding ties one object to another; for example, a pod is bound to a node by a scheduler. Deprecated in 1.7, please use the bindings subresource of pods instead. */

public struct V1Binding: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var target: V1ObjectReference

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, target: V1ObjectReference) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.target = target
    }


}

