//
// V1ClusterRoleBinding.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in the global namespace, and adds who information via Subject. */

public struct V1ClusterRoleBinding: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var roleRef: V1RoleRef
    /** Subjects holds references to the objects the role applies to. */
    public var subjects: [V1Subject]?

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, roleRef: V1RoleRef, subjects: [V1Subject]?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.roleRef = roleRef
        self.subjects = subjects
    }


}

