//
// V1ClientIPConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ClientIPConfig represents the configurations of Client IP based session affinity. */

public struct V1ClientIPConfig: Codable {

    /** timeoutSeconds specifies the seconds of ClientIP type session sticky time. The value must be &gt;0 &amp;&amp; &lt;&#x3D;86400(for 1 day) if ServiceAffinity &#x3D;&#x3D; \&quot;ClientIP\&quot;. Default value is 10800(for 3 hours). */
    public var timeoutSeconds: Int?

    public init(timeoutSeconds: Int?) {
        self.timeoutSeconds = timeoutSeconds
    }


}

