//
// V1ContainerStateTerminated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ContainerStateTerminated is a terminated state of a container. */

public struct V1ContainerStateTerminated: Codable {

    /** Container&#39;s ID in the format &#39;docker://&lt;container_id&gt;&#39; */
    public var containerID: String?
    /** Exit status from the last termination of the container */
    public var exitCode: Int
    /** Time at which the container last terminated */
    public var finishedAt: Date?
    /** Message regarding the last termination of the container */
    public var message: String?
    /** (brief) reason from the last termination of the container */
    public var reason: String?
    /** Signal from the last termination of the container */
    public var signal: Int?
    /** Time at which previous execution of the container started */
    public var startedAt: Date?

    public init(containerID: String?, exitCode: Int, finishedAt: Date?, message: String?, reason: String?, signal: Int?, startedAt: Date?) {
        self.containerID = containerID
        self.exitCode = exitCode
        self.finishedAt = finishedAt
        self.message = message
        self.reason = reason
        self.signal = signal
        self.startedAt = startedAt
    }


}

