//
// V1ConfigMapEnvSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ConfigMapEnvSource selects a ConfigMap to populate the environment variables with.  The contents of the target ConfigMap&#39;s Data field will represent the key-value pairs as environment variables. */

public struct V1ConfigMapEnvSource: Codable {

    /** Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    public var name: String?
    /** Specify whether the ConfigMap must be defined */
    public var _optional: Bool?

    public init(name: String?, _optional: Bool?) {
        self.name = name
        self._optional = _optional
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _optional = "optional"
    }


}

