//
// V1ComponentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ComponentStatus (and ComponentStatusList) holds the cluster validation info. */

public struct V1ComponentStatus: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** List of component conditions observed */
    public var conditions: [V1ComponentCondition]?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?

    public init(apiVersion: String?, conditions: [V1ComponentCondition]?, kind: String?, metadata: V1ObjectMeta?) {
        self.apiVersion = apiVersion
        self.conditions = conditions
        self.kind = kind
        self.metadata = metadata
    }


}

