//
// V1ContainerStateWaiting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ContainerStateWaiting is a waiting state of a container. */

public struct V1ContainerStateWaiting: Codable {

    /** Message regarding why the container is not yet running. */
    public var message: String?
    /** (brief) reason the container is not yet running. */
    public var reason: String?

    public init(message: String?, reason: String?) {
        self.message = message
        self.reason = reason
    }


}

