//
// V1ConfigMapKeySelector.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Selects a key from a ConfigMap. */

public struct V1ConfigMapKeySelector: Codable {

    /** The key to select. */
    public var key: String
    /** Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    public var name: String?
    /** Specify whether the ConfigMap or its key must be defined */
    public var _optional: Bool?

    public init(key: String, name: String?, _optional: Bool?) {
        self.key = key
        self.name = name
        self._optional = _optional
    }

    public enum CodingKeys: String, CodingKey { 
        case key
        case name
        case _optional = "optional"
    }


}

