//
// V1ComponentCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Information about the condition of a component. */

public struct V1ComponentCondition: Codable {

    /** Condition error code for a component. For example, a health check error code. */
    public var error: String?
    /** Message about the condition for a component. For example, information about a health check. */
    public var message: String?
    /** Status of the condition for a component. Valid values for \&quot;Healthy\&quot;: \&quot;True\&quot;, \&quot;False\&quot;, or \&quot;Unknown\&quot;. */
    public var status: String
    /** Type of condition for a component. Valid value: \&quot;Healthy\&quot; */
    public var type: String

    public init(error: String?, message: String?, status: String, type: String) {
        self.error = error
        self.message = message
        self.status = status
        self.type = type
    }


}

