//
// V1ConfigMapProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Adapts a ConfigMap into a projected volume.  The contents of the target ConfigMap&#39;s Data field will be presented in a projected volume as files using the keys in the Data field as the file names, unless the items element is populated with specific mappings of keys to paths. Note that this is identical to a configmap volume source without the default mode. */

public struct V1ConfigMapProjection: Codable {

    /** If unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the &#39;..&#39; path or start with &#39;..&#39;. */
    public var items: [V1KeyToPath]?
    /** Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    public var name: String?
    /** Specify whether the ConfigMap or its keys must be defined */
    public var _optional: Bool?

    public init(items: [V1KeyToPath]?, name: String?, _optional: Bool?) {
        self.items = items
        self.name = name
        self._optional = _optional
    }

    public enum CodingKeys: String, CodingKey { 
        case items
        case name
        case _optional = "optional"
    }


}

