//
// V1CrossVersionObjectReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CrossVersionObjectReference contains enough information to let you identify the referred resource. */

public struct V1CrossVersionObjectReference: Codable {

    /** API version of the referent */
    public var apiVersion: String?
    /** Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds\&quot; */
    public var kind: String
    /** Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names */
    public var name: String

    public init(apiVersion: String?, kind: String, name: String) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.name = name
    }


}

