//
// V1CSINodeSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CSINodeSpec holds information about the specification of all CSI drivers installed on a node */

public struct V1CSINodeSpec: Codable {

    /** drivers is a list of information of all CSI Drivers existing on a node. If all drivers in the list are uninstalled, this can become empty. */
    public var drivers: [V1CSINodeDriver]

    public init(drivers: [V1CSINodeDriver]) {
        self.drivers = drivers
    }


}

