//
// V1CSIVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a source location of a volume to mount, managed by an external CSI driver */

public struct V1CSIVolumeSource: Codable {

    /** Driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster. */
    public var driver: String
    /** Filesystem type to mount. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply. */
    public var fsType: String?
    public var nodePublishSecretRef: V1LocalObjectReference?
    /** Specifies a read-only configuration for the volume. Defaults to false (read/write). */
    public var readOnly: Bool?
    /** VolumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver&#39;s documentation for supported values. */
    public var volumeAttributes: [String:String]?

    public init(driver: String, fsType: String?, nodePublishSecretRef: V1LocalObjectReference?, readOnly: Bool?, volumeAttributes: [String:String]?) {
        self.driver = driver
        self.fsType = fsType
        self.nodePublishSecretRef = nodePublishSecretRef
        self.readOnly = readOnly
        self.volumeAttributes = volumeAttributes
    }


}

