//
// V1CustomResourceValidation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CustomResourceValidation is a list of validation methods for CustomResources. */

public struct V1CustomResourceValidation: Codable {

    public var openAPIV3Schema: V1JSONSchemaProps?

    public init(openAPIV3Schema: V1JSONSchemaProps?) {
        self.openAPIV3Schema = openAPIV3Schema
    }


}

