//
// V1CustomResourceConversion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CustomResourceConversion describes how to convert different versions of a CR. */

public struct V1CustomResourceConversion: Codable {

    /** strategy specifies how custom resources are converted between versions. Allowed values are: - &#x60;None&#x60;: The converter only change the apiVersion and would not touch any other field in the custom resource. - &#x60;Webhook&#x60;: API Server will call to an external webhook to do the conversion. Additional information   is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set. */
    public var strategy: String
    public var webhook: V1WebhookConversion?

    public init(strategy: String, webhook: V1WebhookConversion?) {
        self.strategy = strategy
        self.webhook = webhook
    }


}

