//
// V1DaemonEndpoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DaemonEndpoint contains information about a single Daemon endpoint. */

public struct V1DaemonEndpoint: Codable {

    /** Port number of the given endpoint. */
    public var port: Int

    public init(port: Int) {
        self.port = port
    }

    public enum CodingKeys: String, CodingKey { 
        case port = "Port"
    }


}

