//
// V1DownwardAPIVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DownwardAPIVolumeSource represents a volume containing downward API info. Downward API volumes support ownership management and SELinux relabeling. */

public struct V1DownwardAPIVolumeSource: Codable {

    /** Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. */
    public var defaultMode: Int?
    /** Items is a list of downward API volume file */
    public var items: [V1DownwardAPIVolumeFile]?

    public init(defaultMode: Int?, items: [V1DownwardAPIVolumeFile]?) {
        self.defaultMode = defaultMode
        self.items = items
    }


}

