//
// V1DownwardAPIVolumeFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** DownwardAPIVolumeFile represents information to create the file containing the pod field */

public struct V1DownwardAPIVolumeFile: Codable {

    public var fieldRef: V1ObjectFieldSelector?
    /** Optional: mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. */
    public var mode: Int?
    /** Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the &#39;..&#39; path. Must be utf-8 encoded. The first item of the relative path must not start with &#39;..&#39; */
    public var path: String
    public var resourceFieldRef: V1ResourceFieldSelector?

    public init(fieldRef: V1ObjectFieldSelector?, mode: Int?, path: String, resourceFieldRef: V1ResourceFieldSelector?) {
        self.fieldRef = fieldRef
        self.mode = mode
        self.path = path
        self.resourceFieldRef = resourceFieldRef
    }


}

