//
// V1EnvVarSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** EnvVarSource represents a source for the value of an EnvVar. */

public struct V1EnvVarSource: Codable {

    public var configMapKeyRef: V1ConfigMapKeySelector?
    public var fieldRef: V1ObjectFieldSelector?
    public var resourceFieldRef: V1ResourceFieldSelector?
    public var secretKeyRef: V1SecretKeySelector?

    public init(configMapKeyRef: V1ConfigMapKeySelector?, fieldRef: V1ObjectFieldSelector?, resourceFieldRef: V1ResourceFieldSelector?, secretKeyRef: V1SecretKeySelector?) {
        self.configMapKeyRef = configMapKeyRef
        self.fieldRef = fieldRef
        self.resourceFieldRef = resourceFieldRef
        self.secretKeyRef = secretKeyRef
    }


}

