//
// V1EnvVar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** EnvVar represents an environment variable present in a Container. */

public struct V1EnvVar: Codable {

    /** Name of the environment variable. Must be a C_IDENTIFIER. */
    public var name: String
    /** Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \&quot;\&quot;. */
    public var value: String?
    public var valueFrom: V1EnvVarSource?

    public init(name: String, value: String?, valueFrom: V1EnvVarSource?) {
        self.name = name
        self.value = value
        self.valueFrom = valueFrom
    }


}

