//
// V1EventSeries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time. */

public struct V1EventSeries: Codable {

    /** Number of occurrences in this series up to the last heartbeat time */
    public var count: Int?
    /** Time of the last occurrence observed */
    public var lastObservedTime: Date?
    /** State of this Series: Ongoing or Finished Deprecated. Planned removal for 1.18 */
    public var state: String?

    public init(count: Int?, lastObservedTime: Date?, state: String?) {
        self.count = count
        self.lastObservedTime = lastObservedTime
        self.state = state
    }


}

