//
// V1FCVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a Fibre Channel volume. Fibre Channel volumes can only be mounted as read/write once. Fibre Channel volumes support ownership management and SELinux relabeling. */

public struct V1FCVolumeSource: Codable {

    /** Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified. */
    public var fsType: String?
    /** Optional: FC target lun number */
    public var lun: Int?
    /** Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    public var readOnly: Bool?
    /** Optional: FC target worldwide names (WWNs) */
    public var targetWWNs: [String]?
    /** Optional: FC volume world wide identifiers (wwids) Either wwids or combination of targetWWNs and lun must be set, but not both simultaneously. */
    public var wwids: [String]?

    public init(fsType: String?, lun: Int?, readOnly: Bool?, targetWWNs: [String]?, wwids: [String]?) {
        self.fsType = fsType
        self.lun = lun
        self.readOnly = readOnly
        self.targetWWNs = targetWWNs
        self.wwids = wwids
    }


}

