//
// V1FlexPersistentVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** FlexPersistentVolumeSource represents a generic persistent volume resource that is provisioned/attached using an exec based plugin. */

public struct V1FlexPersistentVolumeSource: Codable {

    /** Driver is the name of the driver to use for this volume. */
    public var driver: String
    /** Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. The default filesystem depends on FlexVolume script. */
    public var fsType: String?
    /** Optional: Extra command options if any. */
    public var options: [String:String]?
    /** Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    public var readOnly: Bool?
    public var secretRef: V1SecretReference?

    public init(driver: String, fsType: String?, options: [String:String]?, readOnly: Bool?, secretRef: V1SecretReference?) {
        self.driver = driver
        self.fsType = fsType
        self.options = options
        self.readOnly = readOnly
        self.secretRef = secretRef
    }


}

