//
// V1FlockerVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a Flocker volume mounted by the Flocker agent. One and only one of datasetName and datasetUUID should be set. Flocker volumes do not support ownership management or SELinux relabeling. */

public struct V1FlockerVolumeSource: Codable {

    /** Name of the dataset stored as metadata -&gt; name on the dataset for Flocker should be considered as deprecated */
    public var datasetName: String?
    /** UUID of the dataset. This is unique identifier of a Flocker dataset */
    public var datasetUUID: String?

    public init(datasetName: String?, datasetUUID: String?) {
        self.datasetName = datasetName
        self.datasetUUID = datasetUUID
    }


}

