//
// V1GitRepoVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a volume that is populated with the contents of a git repository. Git repo volumes do not support ownership management. Git repo volumes support SELinux relabeling.  DEPRECATED: GitRepo is deprecated. To provision a container with a git repo, mount an EmptyDir into an InitContainer that clones the repo using git, then mount the EmptyDir into the Pod&#39;s container. */

public struct V1GitRepoVolumeSource: Codable {

    /** Target directory name. Must not contain or start with &#39;..&#39;.  If &#39;.&#39; is supplied, the volume directory will be the git repository.  Otherwise, if specified, the volume will contain the git repository in the subdirectory with the given name. */
    public var directory: String?
    /** Repository URL */
    public var repository: String
    /** Commit hash for the specified revision. */
    public var revision: String?

    public init(directory: String?, repository: String, revision: String?) {
        self.directory = directory
        self.repository = repository
        self.revision = revision
    }


}

