//
// V1GroupVersionForDiscovery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** GroupVersion contains the \&quot;group/version\&quot; and \&quot;version\&quot; string of a version. It is made a struct to keep extensibility. */

public struct V1GroupVersionForDiscovery: Codable {

    /** groupVersion specifies the API group and version in the form \&quot;group/version\&quot; */
    public var groupVersion: String
    /** version specifies the version in the form of \&quot;version\&quot;. This is to save the clients the trouble of splitting the GroupVersion. */
    public var version: String

    public init(groupVersion: String, version: String) {
        self.groupVersion = groupVersion
        self.version = version
    }


}

