//
// V1HostAlias.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod&#39;s hosts file. */

public struct V1HostAlias: Codable {

    /** Hostnames for the above IP address. */
    public var hostnames: [String]?
    /** IP address of the host file entry. */
    public var ip: String?

    public init(hostnames: [String]?, ip: String?) {
        self.hostnames = hostnames
        self.ip = ip
    }


}

