//
// V1HorizontalPodAutoscalerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** current status of a horizontal pod autoscaler */

public struct V1HorizontalPodAutoscalerStatus: Codable {

    /** current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU. */
    public var currentCPUUtilizationPercentage: Int?
    /** current number of replicas of pods managed by this autoscaler. */
    public var currentReplicas: Int
    /** desired number of replicas of pods managed by this autoscaler. */
    public var desiredReplicas: Int
    /** last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed. */
    public var lastScaleTime: Date?
    /** most recent generation observed by this autoscaler. */
    public var observedGeneration: Int64?

    public init(currentCPUUtilizationPercentage: Int?, currentReplicas: Int, desiredReplicas: Int, lastScaleTime: Date?, observedGeneration: Int64?) {
        self.currentCPUUtilizationPercentage = currentCPUUtilizationPercentage
        self.currentReplicas = currentReplicas
        self.desiredReplicas = desiredReplicas
        self.lastScaleTime = lastScaleTime
        self.observedGeneration = observedGeneration
    }


}

