//
// V1JobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** JobStatus represents the current state of a Job. */

public struct V1JobStatus: Codable {

    /** The number of actively running pods. */
    public var active: Int?
    /** Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. */
    public var completionTime: Date?
    /** The latest available observations of an object&#39;s current state. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ */
    public var conditions: [V1JobCondition]?
    /** The number of pods which reached phase Failed. */
    public var failed: Int?
    /** Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. */
    public var startTime: Date?
    /** The number of pods which reached phase Succeeded. */
    public var succeeded: Int?

    public init(active: Int?, completionTime: Date?, conditions: [V1JobCondition]?, failed: Int?, startTime: Date?, succeeded: Int?) {
        self.active = active
        self.completionTime = completionTime
        self.conditions = conditions
        self.failed = failed
        self.startTime = startTime
        self.succeeded = succeeded
    }


}

