//
// V1LimitRangeItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** LimitRangeItem defines a min/max usage limit for any resource that matches on kind. */

public struct V1LimitRangeItem: Codable {

    /** Default resource requirement limit value by resource name if resource limit is omitted. */
    public var _default: [String:String]?
    /** DefaultRequest is the default resource requirement request value by resource name if resource request is omitted. */
    public var defaultRequest: [String:String]?
    /** Max usage constraints on this kind by resource name. */
    public var max: [String:String]?
    /** MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource. */
    public var maxLimitRequestRatio: [String:String]?
    /** Min usage constraints on this kind by resource name. */
    public var min: [String:String]?
    /** Type of resource that this limit applies to. */
    public var type: String?

    public init(_default: [String:String]?, defaultRequest: [String:String]?, max: [String:String]?, maxLimitRequestRatio: [String:String]?, min: [String:String]?, type: String?) {
        self._default = _default
        self.defaultRequest = defaultRequest
        self.max = max
        self.maxLimitRequestRatio = maxLimitRequestRatio
        self.min = min
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _default = "default"
        case defaultRequest
        case max
        case maxLimitRequestRatio
        case min
        case type
    }


}

