//
// V1Lifecycle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted. */

public struct V1Lifecycle: Codable {

    public var postStart: V1Handler?
    public var preStop: V1Handler?

    public init(postStart: V1Handler?, preStop: V1Handler?) {
        self.postStart = postStart
        self.preStop = preStop
    }


}

