//
// V1LocalObjectReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace. */

public struct V1LocalObjectReference: Codable {

    /** Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    public var name: String?

    public init(name: String?) {
        self.name = name
    }


}

