//
// V1LoadBalancerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** LoadBalancerStatus represents the status of a load-balancer. */

public struct V1LoadBalancerStatus: Codable {

    /** Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points. */
    public var ingress: [V1LoadBalancerIngress]?

    public init(ingress: [V1LoadBalancerIngress]?) {
        self.ingress = ingress
    }


}

