//
// V1LoadBalancerIngress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point. */

public struct V1LoadBalancerIngress: Codable {

    /** Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers) */
    public var hostname: String?
    /** IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers) */
    public var ip: String?

    public init(hostname: String?, ip: String?) {
        self.hostname = hostname
        self.ip = ip
    }


}

