//
// V1NamespaceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** NamespaceStatus is information about the current status of a Namespace. */

public struct V1NamespaceStatus: Codable {

    /** Represents the latest available observations of a namespace&#39;s current state. */
    public var conditions: [V1NamespaceCondition]?
    /** Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/ */
    public var phase: String?

    public init(conditions: [V1NamespaceCondition]?, phase: String?) {
        self.conditions = conditions
        self.phase = phase
    }


}

