//
// V1NFSVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents an NFS mount that lasts the lifetime of a pod. NFS volumes do not support ownership management or SELinux relabeling. */

public struct V1NFSVolumeSource: Codable {

    /** Path that is exported by the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    public var path: String
    /** ReadOnly here will force the NFS export to be mounted with read-only permissions. Defaults to false. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    public var readOnly: Bool?
    /** Server is the hostname or IP address of the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    public var server: String

    public init(path: String, readOnly: Bool?, server: String) {
        self.path = path
        self.readOnly = readOnly
        self.server = server
    }


}

