//
// V1NodeSelectorTerm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm. */

public struct V1NodeSelectorTerm: Codable {

    /** A list of node selector requirements by node&#39;s labels. */
    public var matchExpressions: [V1NodeSelectorRequirement]?
    /** A list of node selector requirements by node&#39;s fields. */
    public var matchFields: [V1NodeSelectorRequirement]?

    public init(matchExpressions: [V1NodeSelectorRequirement]?, matchFields: [V1NodeSelectorRequirement]?) {
        self.matchExpressions = matchExpressions
        self.matchFields = matchFields
    }


}

