//
// V1NodeAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** NodeAddress contains information for the node&#39;s address. */

public struct V1NodeAddress: Codable {

    /** The node address. */
    public var address: String
    /** Node address type, one of Hostname, ExternalIP or InternalIP. */
    public var type: String

    public init(address: String, type: String) {
        self.address = address
        self.type = type
    }


}

