//
// V1NodeCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** NodeCondition contains condition information for a node. */

public struct V1NodeCondition: Codable {

    /** Last time we got an update on a given condition. */
    public var lastHeartbeatTime: Date?
    /** Last time the condition transit from one status to another. */
    public var lastTransitionTime: Date?
    /** Human readable message indicating details about last transition. */
    public var message: String?
    /** (brief) reason for the condition&#39;s last transition. */
    public var reason: String?
    /** Status of the condition, one of True, False, Unknown. */
    public var status: String
    /** Type of node condition. */
    public var type: String

    public init(lastHeartbeatTime: Date?, lastTransitionTime: Date?, message: String?, reason: String?, status: String, type: String) {
        self.lastHeartbeatTime = lastHeartbeatTime
        self.lastTransitionTime = lastTransitionTime
        self.message = message
        self.reason = reason
        self.status = status
        self.type = type
    }


}

