//
// V1NonResourceRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** NonResourceRule holds information that describes a rule for the non-resource */

public struct V1NonResourceRule: Codable {

    /** NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path.  \&quot;*\&quot; means all. */
    public var nonResourceURLs: [String]?
    /** Verb is a list of kubernetes non-resource API verbs, like: get, post, put, delete, patch, head, options.  \&quot;*\&quot; means all. */
    public var verbs: [String]

    public init(nonResourceURLs: [String]?, verbs: [String]) {
        self.nonResourceURLs = nonResourceURLs
        self.verbs = verbs
    }


}

