//
// V1NodeAffinity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Node affinity is a group of node affinity scheduling rules. */

public struct V1NodeAffinity: Codable {

    /** The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding \&quot;weight\&quot; to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred. */
    public var preferredDuringSchedulingIgnoredDuringExecution: [V1PreferredSchedulingTerm]?
    public var requiredDuringSchedulingIgnoredDuringExecution: V1NodeSelector?

    public init(preferredDuringSchedulingIgnoredDuringExecution: [V1PreferredSchedulingTerm]?, requiredDuringSchedulingIgnoredDuringExecution: V1NodeSelector?) {
        self.preferredDuringSchedulingIgnoredDuringExecution = preferredDuringSchedulingIgnoredDuringExecution
        self.requiredDuringSchedulingIgnoredDuringExecution = requiredDuringSchedulingIgnoredDuringExecution
    }


}

