//
// V1NodeSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** NodeSpec describes the attributes that a node is created with. */

public struct V1NodeSpec: Codable {

    public var configSource: V1NodeConfigSource?
    /** Deprecated. Not all kubelets will set this field. Remove field after 1.13. see: https://issues.k8s.io/61966 */
    public var externalID: String?
    /** PodCIDR represents the pod IP range assigned to the node. */
    public var podCIDR: String?
    /** podCIDRs represents the IP ranges assigned to the node for usage by Pods on that node. If this field is specified, the 0th entry must match the podCIDR field. It may contain at most 1 value for each of IPv4 and IPv6. */
    public var podCIDRs: [String]?
    /** ID of the node assigned by the cloud provider in the format: &lt;ProviderName&gt;://&lt;ProviderSpecificNodeID&gt; */
    public var providerID: String?
    /** If specified, the node&#39;s taints. */
    public var taints: [V1Taint]?
    /** Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration */
    public var unschedulable: Bool?

    public init(configSource: V1NodeConfigSource?, externalID: String?, podCIDR: String?, podCIDRs: [String]?, providerID: String?, taints: [V1Taint]?, unschedulable: Bool?) {
        self.configSource = configSource
        self.externalID = externalID
        self.podCIDR = podCIDR
        self.podCIDRs = podCIDRs
        self.providerID = providerID
        self.taints = taints
        self.unschedulable = unschedulable
    }


}

