//
// V1NodeSelector.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms. */

public struct V1NodeSelector: Codable {

    /** Required. A list of node selector terms. The terms are ORed. */
    public var nodeSelectorTerms: [V1NodeSelectorTerm]

    public init(nodeSelectorTerms: [V1NodeSelectorTerm]) {
        self.nodeSelectorTerms = nodeSelectorTerms
    }


}

