//
// V1ObjectFieldSelector.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ObjectFieldSelector selects an APIVersioned field of an object. */

public struct V1ObjectFieldSelector: Codable {

    /** Version of the schema the FieldPath is written in terms of, defaults to \&quot;v1\&quot;. */
    public var apiVersion: String?
    /** Path of the field to select in the specified API version. */
    public var fieldPath: String

    public init(apiVersion: String?, fieldPath: String) {
        self.apiVersion = apiVersion
        self.fieldPath = fieldPath
    }


}

