//
// V1PersistentVolumeClaimStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PersistentVolumeClaimStatus is the current status of a persistent volume claim. */

public struct V1PersistentVolumeClaimStatus: Codable {

    /** AccessModes contains the actual access modes the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
    public var accessModes: [String]?
    /** Represents the actual resources of the underlying volume. */
    public var capacity: [String:String]?
    /** Current Condition of persistent volume claim. If underlying persistent volume is being resized then the Condition will be set to &#39;ResizeStarted&#39;. */
    public var conditions: [V1PersistentVolumeClaimCondition]?
    /** Phase represents the current phase of PersistentVolumeClaim. */
    public var phase: String?

    public init(accessModes: [String]?, capacity: [String:String]?, conditions: [V1PersistentVolumeClaimCondition]?, phase: String?) {
        self.accessModes = accessModes
        self.capacity = capacity
        self.conditions = conditions
        self.phase = phase
    }


}

