//
// V1PersistentVolumeClaimSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes */

public struct V1PersistentVolumeClaimSpec: Codable {

    /** AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
    public var accessModes: [String]?
    public var dataSource: V1TypedLocalObjectReference?
    public var resources: V1ResourceRequirements?
    public var selector: V1LabelSelector?
    /** Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1 */
    public var storageClassName: String?
    /** volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec. This is a beta feature. */
    public var volumeMode: String?
    /** VolumeName is the binding reference to the PersistentVolume backing this claim. */
    public var volumeName: String?

    public init(accessModes: [String]?, dataSource: V1TypedLocalObjectReference?, resources: V1ResourceRequirements?, selector: V1LabelSelector?, storageClassName: String?, volumeMode: String?, volumeName: String?) {
        self.accessModes = accessModes
        self.dataSource = dataSource
        self.resources = resources
        self.selector = selector
        self.storageClassName = storageClassName
        self.volumeMode = volumeMode
        self.volumeName = volumeName
    }


}

