//
// V1PersistentVolumeClaimCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PersistentVolumeClaimCondition contails details about state of pvc */

public struct V1PersistentVolumeClaimCondition: Codable {

    /** Last time we probed the condition. */
    public var lastProbeTime: Date?
    /** Last time the condition transitioned from one status to another. */
    public var lastTransitionTime: Date?
    /** Human-readable message indicating details about last transition. */
    public var message: String?
    /** Unique, this should be a short, machine understandable string that gives the reason for condition&#39;s last transition. If it reports \&quot;ResizeStarted\&quot; that means the underlying persistent volume is being resized. */
    public var reason: String?
    public var status: String
    public var type: String

    public init(lastProbeTime: Date?, lastTransitionTime: Date?, message: String?, reason: String?, status: String, type: String) {
        self.lastProbeTime = lastProbeTime
        self.lastTransitionTime = lastTransitionTime
        self.message = message
        self.reason = reason
        self.status = status
        self.type = type
    }


}

