//
// V1PhotonPersistentDiskVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a Photon Controller persistent disk resource. */

public struct V1PhotonPersistentDiskVolumeSource: Codable {

    /** Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified. */
    public var fsType: String?
    /** ID that identifies Photon Controller persistent disk */
    public var pdID: String

    public init(fsType: String?, pdID: String) {
        self.fsType = fsType
        self.pdID = pdID
    }


}

