//
// V1PodTemplateSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodTemplateSpec describes the data a pod should have when created from a template */

public struct V1PodTemplateSpec: Codable {

    public var metadata: V1ObjectMeta?
    public var spec: V1PodSpec?

    public init(metadata: V1ObjectMeta?, spec: V1PodSpec?) {
        self.metadata = metadata
        self.spec = spec
    }


}

