//
// V1PodCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodCondition contains details for the current condition of this pod. */

public struct V1PodCondition: Codable {

    /** Last time we probed the condition. */
    public var lastProbeTime: Date?
    /** Last time the condition transitioned from one status to another. */
    public var lastTransitionTime: Date?
    /** Human-readable message indicating details about last transition. */
    public var message: String?
    /** Unique, one-word, CamelCase reason for the condition&#39;s last transition. */
    public var reason: String?
    /** Status is the status of the condition. Can be True, False, Unknown. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions */
    public var status: String
    /** Type is the type of the condition. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions */
    public var type: String

    public init(lastProbeTime: Date?, lastTransitionTime: Date?, message: String?, reason: String?, status: String, type: String) {
        self.lastProbeTime = lastProbeTime
        self.lastTransitionTime = lastTransitionTime
        self.message = message
        self.reason = reason
        self.status = status
        self.type = type
    }


}

