//
// V1PodReadinessGate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodReadinessGate contains the reference to a pod condition */

public struct V1PodReadinessGate: Codable {

    /** ConditionType refers to a condition in the pod&#39;s condition list with matching type. */
    public var conditionType: String

    public init(conditionType: String) {
        self.conditionType = conditionType
    }


}

