//
// V1PodDNSConfigOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodDNSConfigOption defines DNS resolver options of a pod. */

public struct V1PodDNSConfigOption: Codable {

    /** Required. */
    public var name: String?
    public var value: String?

    public init(name: String?, value: String?) {
        self.name = name
        self.value = value
    }


}

