//
// V1ProjectedVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a projected volume source */

public struct V1ProjectedVolumeSource: Codable {

    /** Mode bits to use on created files by default. Must be a value between 0 and 0777. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. */
    public var defaultMode: Int?
    /** list of volume projections */
    public var sources: [V1VolumeProjection]

    public init(defaultMode: Int?, sources: [V1VolumeProjection]) {
        self.defaultMode = defaultMode
        self.sources = sources
    }


}

