//
// V1PriorityClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PriorityClass defines mapping from a priority class name to the priority integer value. The value can be any valid integer. */

public struct V1PriorityClass: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** description is an arbitrary string that usually provides guidelines on when this priority class should be used. */
    public var _description: String?
    /** globalDefault specifies whether this PriorityClass should be considered as the default priority for pods that do not have any priority class. Only one PriorityClass can be marked as &#x60;globalDefault&#x60;. However, if more than one PriorityClasses exists with their &#x60;globalDefault&#x60; field set to true, the smallest value of such global default PriorityClasses will be used as the default priority. */
    public var globalDefault: Bool?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    /** PreemptionPolicy is the Policy for preempting pods with lower priority. One of Never, PreemptLowerPriority. Defaults to PreemptLowerPriority if unset. This field is alpha-level and is only honored by servers that enable the NonPreemptingPriority feature. */
    public var preemptionPolicy: String?
    /** The value of this priority class. This is the actual priority that pods receive when they have the name of this class in their pod spec. */
    public var value: Int

    public init(apiVersion: String?, _description: String?, globalDefault: Bool?, kind: String?, metadata: V1ObjectMeta?, preemptionPolicy: String?, value: Int) {
        self.apiVersion = apiVersion
        self._description = _description
        self.globalDefault = globalDefault
        self.kind = kind
        self.metadata = metadata
        self.preemptionPolicy = preemptionPolicy
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case apiVersion
        case _description = "description"
        case globalDefault
        case kind
        case metadata
        case preemptionPolicy
        case value
    }


}

