//
// V1Preconditions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out. */

public struct V1Preconditions: Codable {

    /** Specifies the target ResourceVersion */
    public var resourceVersion: String?
    /** Specifies the target UID. */
    public var uid: String?

    public init(resourceVersion: String?, uid: String?) {
        self.resourceVersion = resourceVersion
        self.uid = uid
    }


}

