//
// V1ResourceQuotaStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ResourceQuotaStatus defines the enforced hard limits and observed use. */

public struct V1ResourceQuotaStatus: Codable {

    /** Hard is the set of enforced hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/ */
    public var hard: [String:String]?
    /** Used is the current observed total usage of the resource in the namespace. */
    public var used: [String:String]?

    public init(hard: [String:String]?, used: [String:String]?) {
        self.hard = hard
        self.used = used
    }


}

