//
// V1ResourceQuotaSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ResourceQuotaSpec defines the desired hard limits to enforce for Quota. */

public struct V1ResourceQuotaSpec: Codable {

    /** hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/ */
    public var hard: [String:String]?
    public var scopeSelector: V1ScopeSelector?
    /** A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects. */
    public var scopes: [String]?

    public init(hard: [String:String]?, scopeSelector: V1ScopeSelector?, scopes: [String]?) {
        self.hard = hard
        self.scopeSelector = scopeSelector
        self.scopes = scopes
    }


}

