//
// V1ScopeSelector.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** A scope selector represents the AND of the selectors represented by the scoped-resource selector requirements. */

public struct V1ScopeSelector: Codable {

    /** A list of scope selector requirements by scope of the resources. */
    public var matchExpressions: [V1ScopedResourceSelectorRequirement]?

    public init(matchExpressions: [V1ScopedResourceSelectorRequirement]?) {
        self.matchExpressions = matchExpressions
    }


}

