//
// V1ScaleStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ScaleStatus represents the current status of a scale subresource. */

public struct V1ScaleStatus: Codable {

    /** actual number of observed instances of the scaled object. */
    public var replicas: Int
    /** label query over pods that should match the replicas count. This is same as the label selector but in the string format to avoid introspection by clients. The string will be in the same format as the query-param syntax. More info about label selectors: http://kubernetes.io/docs/user-guide/labels#label-selectors */
    public var selector: String?

    public init(replicas: Int, selector: String?) {
        self.replicas = replicas
        self.selector = selector
    }


}

