//
// V1ScopedResourceSelectorRequirement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values. */

public struct V1ScopedResourceSelectorRequirement: Codable {

    /** Represents a scope&#39;s relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. */
    public var _operator: String
    /** The name of the scope that the selector applies to. */
    public var scopeName: String
    /** An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch. */
    public var values: [String]?

    public init(_operator: String, scopeName: String, values: [String]?) {
        self._operator = _operator
        self.scopeName = scopeName
        self.values = values
    }

    public enum CodingKeys: String, CodingKey { 
        case _operator = "operator"
        case scopeName
        case values
    }


}

