//
// V1SelfSubjectAccessReviewSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set */

public struct V1SelfSubjectAccessReviewSpec: Codable {

    public var nonResourceAttributes: V1NonResourceAttributes?
    public var resourceAttributes: V1ResourceAttributes?

    public init(nonResourceAttributes: V1NonResourceAttributes?, resourceAttributes: V1ResourceAttributes?) {
        self.nonResourceAttributes = nonResourceAttributes
        self.resourceAttributes = resourceAttributes
    }


}

