//
// V1SessionAffinityConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** SessionAffinityConfig represents the configurations of session affinity. */

public struct V1SessionAffinityConfig: Codable {

    public var clientIP: V1ClientIPConfig?

    public init(clientIP: V1ClientIPConfig?) {
        self.clientIP = clientIP
    }


}

