//
// V1SelfSubjectRulesReviewSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct V1SelfSubjectRulesReviewSpec: Codable {

    /** Namespace to evaluate rules for. Required. */
    public var namespace: String?

    public init(namespace: String?) {
        self.namespace = namespace
    }


}

