//
// V1ServiceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ServiceStatus represents the current status of a service. */

public struct V1ServiceStatus: Codable {

    public var loadBalancer: V1LoadBalancerStatus?

    public init(loadBalancer: V1LoadBalancerStatus?) {
        self.loadBalancer = loadBalancer
    }


}

