//
// V1SecretVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Adapts a Secret into a volume.  The contents of the target Secret&#39;s Data field will be presented in a volume as files using the keys in the Data field as the file names. Secret volumes support ownership management and SELinux relabeling. */

public struct V1SecretVolumeSource: Codable {

    /** Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. */
    public var defaultMode: Int?
    /** If unspecified, each key-value pair in the Data field of the referenced Secret will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the Secret, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the &#39;..&#39; path or start with &#39;..&#39;. */
    public var items: [V1KeyToPath]?
    /** Specify whether the Secret or its keys must be defined */
    public var _optional: Bool?
    /** Name of the secret in the pod&#39;s namespace to use. More info: https://kubernetes.io/docs/concepts/storage/volumes#secret */
    public var secretName: String?

    public init(defaultMode: Int?, items: [V1KeyToPath]?, _optional: Bool?, secretName: String?) {
        self.defaultMode = defaultMode
        self.items = items
        self._optional = _optional
        self.secretName = secretName
    }

    public enum CodingKeys: String, CodingKey { 
        case defaultMode
        case items
        case _optional = "optional"
        case secretName
    }


}

