//
// V1ServerAddressByClientCIDR.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ServerAddressByClientCIDR helps the client to determine the server address that they should use, depending on the clientCIDR that they match. */

public struct V1ServerAddressByClientCIDR: Codable {

    /** The CIDR with which clients can match their IP to figure out the server address that they should use. */
    public var clientCIDR: String
    /** Address of this server, suitable for a client that matches the above CIDR. This can be a hostname, hostname:port, IP or IP:port. */
    public var serverAddress: String

    public init(clientCIDR: String, serverAddress: String) {
        self.clientCIDR = clientCIDR
        self.serverAddress = serverAddress
    }


}

