//
// V1StatusDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** StatusDetails is a set of additional properties that MAY be set by the server to provide additional information about a response. The Reason field of a Status object defines what attributes will be set. Clients must ignore fields that do not match the defined type of each attribute, and should assume that any attribute may be empty, invalid, or under defined. */

public struct V1StatusDetails: Codable {

    /** The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes. */
    public var causes: [V1StatusCause]?
    /** The group attribute of the resource associated with the status StatusReason. */
    public var group: String?
    /** The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    /** The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described). */
    public var name: String?
    /** If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action. */
    public var retryAfterSeconds: Int?
    /** UID of the resource. (when there is a single resource which can be described). More info: http://kubernetes.io/docs/user-guide/identifiers#uids */
    public var uid: String?

    public init(causes: [V1StatusCause]?, group: String?, kind: String?, name: String?, retryAfterSeconds: Int?, uid: String?) {
        self.causes = causes
        self.group = group
        self.kind = kind
        self.name = name
        self.retryAfterSeconds = retryAfterSeconds
        self.uid = uid
    }


}

