//
// V1StorageOSPersistentVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a StorageOS persistent volume resource. */

public struct V1StorageOSPersistentVolumeSource: Codable {

    /** Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified. */
    public var fsType: String?
    /** Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    public var readOnly: Bool?
    public var secretRef: V1ObjectReference?
    /** VolumeName is the human-readable name of the StorageOS volume.  Volume names are only unique within a namespace. */
    public var volumeName: String?
    /** VolumeNamespace specifies the scope of the volume within StorageOS.  If no namespace is specified then the Pod&#39;s namespace will be used.  This allows the Kubernetes name scoping to be mirrored within StorageOS for tighter integration. Set VolumeName to any name to override the default behaviour. Set to \&quot;default\&quot; if you are not using namespaces within StorageOS. Namespaces that do not pre-exist within StorageOS will be created. */
    public var volumeNamespace: String?

    public init(fsType: String?, readOnly: Bool?, secretRef: V1ObjectReference?, volumeName: String?, volumeNamespace: String?) {
        self.fsType = fsType
        self.readOnly = readOnly
        self.secretRef = secretRef
        self.volumeName = volumeName
        self.volumeNamespace = volumeNamespace
    }


}

