//
// V1Sysctl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Sysctl defines a kernel parameter to be set */

public struct V1Sysctl: Codable {

    /** Name of a property to set */
    public var name: String
    /** Value of a property to set */
    public var value: String

    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }


}

