//
// V1Toleration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** The pod this Toleration is attached to tolerates any taint that matches the triple &lt;key,value,effect&gt; using the matching operator &lt;operator&gt;. */

public struct V1Toleration: Codable {

    /** Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute. */
    public var effect: String?
    /** Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys. */
    public var key: String?
    /** Operator represents a key&#39;s relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category. */
    public var _operator: String?
    /** TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system. */
    public var tolerationSeconds: Int64?
    /** Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string. */
    public var value: String?

    public init(effect: String?, key: String?, _operator: String?, tolerationSeconds: Int64?, value: String?) {
        self.effect = effect
        self.key = key
        self._operator = _operator
        self.tolerationSeconds = tolerationSeconds
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case effect
        case key
        case _operator = "operator"
        case tolerationSeconds
        case value
    }


}

