//
// V1TokenReviewSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** TokenReviewSpec is a description of the token authentication request. */

public struct V1TokenReviewSpec: Codable {

    /** Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver. */
    public var audiences: [String]?
    /** Token is the opaque bearer token. */
    public var token: String?

    public init(audiences: [String]?, token: String?) {
        self.audiences = audiences
        self.token = token
    }


}

