//
// V1TokenRequestStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** TokenRequestStatus is the result of a token request. */

public struct V1TokenRequestStatus: Codable {

    /** ExpirationTimestamp is the time of expiration of the returned token. */
    public var expirationTimestamp: Date
    /** Token is the opaque bearer token. */
    public var token: String

    public init(expirationTimestamp: Date, token: String) {
        self.expirationTimestamp = expirationTimestamp
        self.token = token
    }


}

