//
// V1TokenRequestSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** TokenRequestSpec contains client provided parameters of a token request. */

public struct V1TokenRequestSpec: Codable {

    /** Audiences are the intendend audiences of the token. A recipient of a token must identitfy themself with an identifier in the list of audiences of the token, and otherwise should reject the token. A token issued for multiple audiences may be used to authenticate against any of the audiences listed but implies a high degree of trust between the target audiences. */
    public var audiences: [String]
    public var boundObjectRef: V1BoundObjectReference?
    /** ExpirationSeconds is the requested duration of validity of the request. The token issuer may return a token with a different validity duration so a client needs to check the &#39;expiration&#39; field in a response. */
    public var expirationSeconds: Int64?

    public init(audiences: [String], boundObjectRef: V1BoundObjectReference?, expirationSeconds: Int64?) {
        self.audiences = audiences
        self.boundObjectRef = boundObjectRef
        self.expirationSeconds = expirationSeconds
    }


}

