//
// V1TopologySelectorLabelRequirement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** A topology selector requirement is a selector that matches given label. This is an alpha feature and may change in the future. */

public struct V1TopologySelectorLabelRequirement: Codable {

    /** The label key that the selector applies to. */
    public var key: String
    /** An array of string values. One value must match the label to be selected. Each entry in Values is ORed. */
    public var values: [String]

    public init(key: String, values: [String]) {
        self.key = key
        self.values = values
    }


}

