//
// V1TypedLocalObjectReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** TypedLocalObjectReference contains enough information to let you locate the typed referenced object inside the same namespace. */

public struct V1TypedLocalObjectReference: Codable {

    /** APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required. */
    public var apiGroup: String?
    /** Kind is the type of resource being referenced */
    public var kind: String
    /** Name is the name of resource being referenced */
    public var name: String

    public init(apiGroup: String?, kind: String, name: String) {
        self.apiGroup = apiGroup
        self.kind = kind
        self.name = name
    }


}

