//
// V1UserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** UserInfo holds the information about the user needed to implement the user.Info interface. */

public struct V1UserInfo: Codable {

    /** Any additional information provided by the authenticator. */
    public var extra: [String:[String]]?
    /** The names of groups this user is a part of. */
    public var groups: [String]?
    /** A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs. */
    public var uid: String?
    /** The name that uniquely identifies this user among all active users. */
    public var username: String?

    public init(extra: [String:[String]]?, groups: [String]?, uid: String?, username: String?) {
        self.extra = extra
        self.groups = groups
        self.uid = uid
        self.username = username
    }


}

