//
// V1ValidatingWebhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ValidatingWebhook describes an admission webhook and the resources and operations it applies to. */

public struct V1ValidatingWebhook: Codable {

    /** AdmissionReviewVersions is an ordered list of preferred &#x60;AdmissionReview&#x60; versions the Webhook expects. API server will try to use first version in the list which it supports. If none of the versions specified in this list supported by API server, validation will fail for this object. If a persisted webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail and be subject to the failure policy. */
    public var admissionReviewVersions: [String]
    public var clientConfig: AdmissionregistrationV1WebhookClientConfig
    /** FailurePolicy defines how unrecognized errors from the admission endpoint are handled - allowed values are Ignore or Fail. Defaults to Fail. */
    public var failurePolicy: String?
    /** matchPolicy defines how the \&quot;rules\&quot; list is used to match incoming requests. Allowed values are \&quot;Exact\&quot; or \&quot;Equivalent\&quot;.  - Exact: match a request only if it exactly matches a specified rule. For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1, but \&quot;rules\&quot; only included &#x60;apiGroups:[\&quot;apps\&quot;], apiVersions:[\&quot;v1\&quot;], resources: [\&quot;deployments\&quot;]&#x60;, a request to apps/v1beta1 or extensions/v1beta1 would not be sent to the webhook.  - Equivalent: match a request if modifies a resource listed in rules, even via another API group or version. For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1, and \&quot;rules\&quot; only included &#x60;apiGroups:[\&quot;apps\&quot;], apiVersions:[\&quot;v1\&quot;], resources: [\&quot;deployments\&quot;]&#x60;, a request to apps/v1beta1 or extensions/v1beta1 would be converted to apps/v1 and sent to the webhook.  Defaults to \&quot;Equivalent\&quot; */
    public var matchPolicy: String?
    /** The name of the admission webhook. Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where \&quot;imagepolicy\&quot; is the name of the webhook, and kubernetes.io is the name of the organization. Required. */
    public var name: String
    public var namespaceSelector: V1LabelSelector?
    public var objectSelector: V1LabelSelector?
    /** Rules describes what operations on what resources/subresources the webhook cares about. The webhook cares about an operation if it matches _any_ Rule. However, in order to prevent ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks from putting the cluster in a state which cannot be recovered from without completely disabling the plugin, ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks are never called on admission requests for ValidatingWebhookConfiguration and MutatingWebhookConfiguration objects. */
    public var rules: [V1RuleWithOperations]?
    /** SideEffects states whether this webhook has side effects. Acceptable values are: None, NoneOnDryRun (webhooks created via v1beta1 may also specify Some or Unknown). Webhooks with side effects MUST implement a reconciliation system, since a request may be rejected by a future step in the admission change and the side effects therefore need to be undone. Requests with the dryRun attribute will be auto-rejected if they match a webhook with sideEffects &#x3D;&#x3D; Unknown or Some. */
    public var sideEffects: String
    /** TimeoutSeconds specifies the timeout for this webhook. After the timeout passes, the webhook call will be ignored or the API call will fail based on the failure policy. The timeout value must be between 1 and 30 seconds. Default to 10 seconds. */
    public var timeoutSeconds: Int?

    public init(admissionReviewVersions: [String], clientConfig: AdmissionregistrationV1WebhookClientConfig, failurePolicy: String?, matchPolicy: String?, name: String, namespaceSelector: V1LabelSelector?, objectSelector: V1LabelSelector?, rules: [V1RuleWithOperations]?, sideEffects: String, timeoutSeconds: Int?) {
        self.admissionReviewVersions = admissionReviewVersions
        self.clientConfig = clientConfig
        self.failurePolicy = failurePolicy
        self.matchPolicy = matchPolicy
        self.name = name
        self.namespaceSelector = namespaceSelector
        self.objectSelector = objectSelector
        self.rules = rules
        self.sideEffects = sideEffects
        self.timeoutSeconds = timeoutSeconds
    }


}

