//
// V1VolumeNodeAffinity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from. */

public struct V1VolumeNodeAffinity: Codable {

    public var _required: V1NodeSelector?

    public init(_required: V1NodeSelector?) {
        self._required = _required
    }

    public enum CodingKeys: String, CodingKey { 
        case _required = "required"
    }


}

