//
// V1VolumeProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Projection that may be projected along with other supported volume types */

public struct V1VolumeProjection: Codable {

    public var configMap: V1ConfigMapProjection?
    public var downwardAPI: V1DownwardAPIProjection?
    public var secret: V1SecretProjection?
    public var serviceAccountToken: V1ServiceAccountTokenProjection?

    public init(configMap: V1ConfigMapProjection?, downwardAPI: V1DownwardAPIProjection?, secret: V1SecretProjection?, serviceAccountToken: V1ServiceAccountTokenProjection?) {
        self.configMap = configMap
        self.downwardAPI = downwardAPI
        self.secret = secret
        self.serviceAccountToken = serviceAccountToken
    }


}

