//
// V1VolumeMount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** VolumeMount describes a mounting of a Volume within a container. */

public struct V1VolumeMount: Codable {

    /** Path within the container at which the volume should be mounted.  Must not contain &#39;:&#39;. */
    public var mountPath: String
    /** mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. This field is beta in 1.10. */
    public var mountPropagation: String?
    /** This must match the Name of a Volume. */
    public var name: String
    /** Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. */
    public var readOnly: Bool?
    /** Path within the volume from which the container&#39;s volume should be mounted. Defaults to \&quot;\&quot; (volume&#39;s root). */
    public var subPath: String?
    /** Expanded path within the volume from which the container&#39;s volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container&#39;s environment. Defaults to \&quot;\&quot; (volume&#39;s root). SubPathExpr and SubPath are mutually exclusive. */
    public var subPathExpr: String?

    public init(mountPath: String, mountPropagation: String?, name: String, readOnly: Bool?, subPath: String?, subPathExpr: String?) {
        self.mountPath = mountPath
        self.mountPropagation = mountPropagation
        self.name = name
        self.readOnly = readOnly
        self.subPath = subPath
        self.subPathExpr = subPathExpr
    }


}

