//
// V1VsphereVirtualDiskVolumeSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represents a vSphere volume resource. */

public struct V1VsphereVirtualDiskVolumeSource: Codable {

    /** Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified. */
    public var fsType: String?
    /** Storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName. */
    public var storagePolicyID: String?
    /** Storage Policy Based Management (SPBM) profile name. */
    public var storagePolicyName: String?
    /** Path that identifies vSphere volume vmdk */
    public var volumePath: String

    public init(fsType: String?, storagePolicyID: String?, storagePolicyName: String?, volumePath: String) {
        self.fsType = fsType
        self.storagePolicyID = storagePolicyID
        self.storagePolicyName = storagePolicyName
        self.volumePath = volumePath
    }


}

