//
// V1WebhookConversion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** WebhookConversion describes how to call a conversion webhook */

public struct V1WebhookConversion: Codable {

    public var clientConfig: ApiextensionsV1WebhookClientConfig?
    /** conversionReviewVersions is an ordered list of preferred &#x60;ConversionReview&#x60; versions the Webhook expects. The API server will use the first version in the list which it supports. If none of the versions specified in this list are supported by API server, conversion will fail for the custom resource. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail. */
    public var conversionReviewVersions: [String]

    public init(clientConfig: ApiextensionsV1WebhookClientConfig?, conversionReviewVersions: [String]) {
        self.clientConfig = clientConfig
        self.conversionReviewVersions = conversionReviewVersions
    }


}

