//
// V1WeightedPodAffinityTerm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s) */

public struct V1WeightedPodAffinityTerm: Codable {

    public var podAffinityTerm: V1PodAffinityTerm
    /** weight associated with matching the corresponding podAffinityTerm, in the range 1-100. */
    public var weight: Int

    public init(podAffinityTerm: V1PodAffinityTerm, weight: Int) {
        self.podAffinityTerm = podAffinityTerm
        self.weight = weight
    }


}

