//
// V2alpha1CronJob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** CronJob represents the configuration of a single cron job. */

public struct V2alpha1CronJob: Codable {

    /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
    public var apiVersion: String?
    /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
    public var kind: String?
    public var metadata: V1ObjectMeta?
    public var spec: V2alpha1CronJobSpec?
    public var status: V2alpha1CronJobStatus?

    public init(apiVersion: String?, kind: String?, metadata: V1ObjectMeta?, spec: V2alpha1CronJobSpec?, status: V2alpha1CronJobStatus?) {
        self.apiVersion = apiVersion
        self.kind = kind
        self.metadata = metadata
        self.spec = spec
        self.status = status
    }


}

