//
// V2beta2MetricValueStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** MetricValueStatus holds the current value for a metric */

public struct V2beta2MetricValueStatus: Codable {

    /** currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods. */
    public var averageUtilization: Int?
    /** averageValue is the current value of the average of the metric across all relevant pods (as a quantity) */
    public var averageValue: String?
    /** value is the current value of the metric (as a quantity). */
    public var value: String?

    public init(averageUtilization: Int?, averageValue: String?, value: String?) {
        self.averageUtilization = averageUtilization
        self.averageValue = averageValue
        self.value = value
    }


}

