//
// V2beta1ExternalMetricSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster). Exactly one \&quot;target\&quot; type should be set. */

public struct V2beta1ExternalMetricSource: Codable {

    /** metricName is the name of the metric in question. */
    public var metricName: String
    public var metricSelector: V1LabelSelector?
    /** targetAverageValue is the target per-pod value of global metric (as a quantity). Mutually exclusive with TargetValue. */
    public var targetAverageValue: String?
    /** targetValue is the target value of the metric (as a quantity). Mutually exclusive with TargetAverageValue. */
    public var targetValue: String?

    public init(metricName: String, metricSelector: V1LabelSelector?, targetAverageValue: String?, targetValue: String?) {
        self.metricName = metricName
        self.metricSelector = metricSelector
        self.targetAverageValue = targetAverageValue
        self.targetValue = targetValue
    }


}

