//
// V2beta2ResourceMetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \&quot;pods\&quot; source. */

public struct V2beta2ResourceMetricStatus: Codable {

    public var current: V2beta2MetricValueStatus
    /** Name is the name of the resource in question. */
    public var name: String

    public init(current: V2beta2MetricValueStatus, name: String) {
        self.current = current
        self.name = name
    }


}

