//
// V2beta2MetricTarget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** MetricTarget defines the target value, average value, or average utilization of a specific metric */

public struct V2beta2MetricTarget: Codable {

    /** averageUtilization is the target value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods. Currently only valid for Resource metric source type */
    public var averageUtilization: Int?
    /** averageValue is the target value of the average of the metric across all relevant pods (as a quantity) */
    public var averageValue: String?
    /** type represents whether the metric type is Utilization, Value, or AverageValue */
    public var type: String
    /** value is the target value of the metric (as a quantity). */
    public var value: String?

    public init(averageUtilization: Int?, averageValue: String?, type: String, value: String?) {
        self.averageUtilization = averageUtilization
        self.averageValue = averageValue
        self.type = type
        self.value = value
    }


}

