//
// V2beta2PodsMetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second). */

public struct V2beta2PodsMetricStatus: Codable {

    public var current: V2beta2MetricValueStatus
    public var metric: V2beta2MetricIdentifier

    public init(current: V2beta2MetricValueStatus, metric: V2beta2MetricIdentifier) {
        self.current = current
        self.metric = metric
    }


}

