//
// V2beta1MetricSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** MetricSpec specifies how to scale based on a single metric (only &#x60;type&#x60; and one other matching field should be set at once). */

public struct V2beta1MetricSpec: Codable {

    public var external: V2beta1ExternalMetricSource?
    public var object: V2beta1ObjectMetricSource?
    public var pods: V2beta1PodsMetricSource?
    public var resource: V2beta1ResourceMetricSource?
    /** type is the type of metric source.  It should be one of \&quot;Object\&quot;, \&quot;Pods\&quot; or \&quot;Resource\&quot;, each mapping to a matching field in the object. */
    public var type: String

    public init(external: V2beta1ExternalMetricSource?, object: V2beta1ObjectMetricSource?, pods: V2beta1PodsMetricSource?, resource: V2beta1ResourceMetricSource?, type: String) {
        self.external = external
        self.object = object
        self.pods = pods
        self.resource = resource
        self.type = type
    }


}

