//
// V2beta2ObjectMetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object). */

public struct V2beta2ObjectMetricStatus: Codable {

    public var current: V2beta2MetricValueStatus
    public var describedObject: V2beta2CrossVersionObjectReference
    public var metric: V2beta2MetricIdentifier

    public init(current: V2beta2MetricValueStatus, describedObject: V2beta2CrossVersionObjectReference, metric: V2beta2MetricIdentifier) {
        self.current = current
        self.describedObject = describedObject
        self.metric = metric
    }


}

