//
// V2beta2ExternalMetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object. */

public struct V2beta2ExternalMetricStatus: Codable {

    public var current: V2beta2MetricValueStatus
    public var metric: V2beta2MetricIdentifier

    public init(current: V2beta2MetricValueStatus, metric: V2beta2MetricIdentifier) {
        self.current = current
        self.metric = metric
    }


}

