//
// V2beta1MetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** MetricStatus describes the last-read state of a single metric. */

public struct V2beta1MetricStatus: Codable {

    public var external: V2beta1ExternalMetricStatus?
    public var object: V2beta1ObjectMetricStatus?
    public var pods: V2beta1PodsMetricStatus?
    public var resource: V2beta1ResourceMetricStatus?
    /** type is the type of metric source.  It will be one of \&quot;Object\&quot;, \&quot;Pods\&quot; or \&quot;Resource\&quot;, each corresponds to a matching field in the object. */
    public var type: String

    public init(external: V2beta1ExternalMetricStatus?, object: V2beta1ObjectMetricStatus?, pods: V2beta1PodsMetricStatus?, resource: V2beta1ResourceMetricStatus?, type: String) {
        self.external = external
        self.object = object
        self.pods = pods
        self.resource = resource
        self.type = type
    }


}

