//
// V2beta1ExternalMetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object. */

public struct V2beta1ExternalMetricStatus: Codable {

    /** currentAverageValue is the current value of metric averaged over autoscaled pods. */
    public var currentAverageValue: String?
    /** currentValue is the current value of the metric (as a quantity) */
    public var currentValue: String
    /** metricName is the name of a metric used for autoscaling in metric system. */
    public var metricName: String
    public var metricSelector: V1LabelSelector?

    public init(currentAverageValue: String?, currentValue: String, metricName: String, metricSelector: V1LabelSelector?) {
        self.currentAverageValue = currentAverageValue
        self.currentValue = currentValue
        self.metricName = metricName
        self.metricSelector = metricSelector
    }


}

