//
// V2beta1ObjectMetricStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object). */

public struct V2beta1ObjectMetricStatus: Codable {

    /** averageValue is the current value of the average of the metric across all relevant pods (as a quantity) */
    public var averageValue: String?
    /** currentValue is the current value of the metric (as a quantity). */
    public var currentValue: String
    /** metricName is the name of the metric in question. */
    public var metricName: String
    public var selector: V1LabelSelector?
    public var target: V2beta1CrossVersionObjectReference

    public init(averageValue: String?, currentValue: String, metricName: String, selector: V1LabelSelector?, target: V2beta1CrossVersionObjectReference) {
        self.averageValue = averageValue
        self.currentValue = currentValue
        self.metricName = metricName
        self.selector = selector
        self.target = target
    }


}

