//
// V2beta2ResourceMetricSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** ResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \&quot;pods\&quot; source.  Only one \&quot;target\&quot; type should be set. */

public struct V2beta2ResourceMetricSource: Codable {

    /** name is the name of the resource in question. */
    public var name: String
    public var target: V2beta2MetricTarget

    public init(name: String, target: V2beta2MetricTarget) {
        self.name = name
        self.target = target
    }


}

